/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LoveReasonCard = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const PhotoCaptions = IDL.Record({
  'graduation' : IDL.Text,
  'winterGarden' : IDL.Text,
  'daughterPhotos' : IDL.Text,
  'berlinMuseum' : IDL.Text,
  'hamptonsNight' : IDL.Text,
  'romeColosseum' : IDL.Text,
  'firstBerlinPhoto' : IDL.Text,
});
export const CardContent = IDL.Record({
  'loveLetter' : IDL.Text,
  'photoCaptions' : PhotoCaptions,
  'reasonCards' : IDL.Vec(LoveReasonCard),
});

export const idlService = IDL.Service({
  'getAllReasonCards' : IDL.Func([], [IDL.Vec(LoveReasonCard)], ['query']),
  'getCardContent' : IDL.Func([], [CardContent], ['query']),
  'getLoveLetter' : IDL.Func([], [IDL.Text], ['query']),
  'getPhotoCaptions' : IDL.Func([], [PhotoCaptions], ['query']),
  'getReasonCard' : IDL.Func([IDL.Nat], [LoveReasonCard], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LoveReasonCard = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const PhotoCaptions = IDL.Record({
    'graduation' : IDL.Text,
    'winterGarden' : IDL.Text,
    'daughterPhotos' : IDL.Text,
    'berlinMuseum' : IDL.Text,
    'hamptonsNight' : IDL.Text,
    'romeColosseum' : IDL.Text,
    'firstBerlinPhoto' : IDL.Text,
  });
  const CardContent = IDL.Record({
    'loveLetter' : IDL.Text,
    'photoCaptions' : PhotoCaptions,
    'reasonCards' : IDL.Vec(LoveReasonCard),
  });
  
  return IDL.Service({
    'getAllReasonCards' : IDL.Func([], [IDL.Vec(LoveReasonCard)], ['query']),
    'getCardContent' : IDL.Func([], [CardContent], ['query']),
    'getLoveLetter' : IDL.Func([], [IDL.Text], ['query']),
    'getPhotoCaptions' : IDL.Func([], [PhotoCaptions], ['query']),
    'getReasonCard' : IDL.Func([IDL.Nat], [LoveReasonCard], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };