/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CardContent {
  'loveLetter' : string,
  'photoCaptions' : PhotoCaptions,
  'reasonCards' : Array<LoveReasonCard>,
}
export interface LoveReasonCard { 'title' : string, 'description' : string }
export interface PhotoCaptions {
  'graduation' : string,
  'winterGarden' : string,
  'daughterPhotos' : string,
  'berlinMuseum' : string,
  'hamptonsNight' : string,
  'romeColosseum' : string,
  'firstBerlinPhoto' : string,
}
export interface _SERVICE {
  'getAllReasonCards' : ActorMethod<[], Array<LoveReasonCard>>,
  'getCardContent' : ActorMethod<[], CardContent>,
  'getLoveLetter' : ActorMethod<[], string>,
  'getPhotoCaptions' : ActorMethod<[], PhotoCaptions>,
  'getReasonCard' : ActorMethod<[bigint], LoveReasonCard>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];