/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LoveCard = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'photos' : IDL.Vec(IDL.Record({ 'src' : IDL.Text, 'rotation' : IDL.Int })),
});
export const GalleryPhoto = IDL.Record({
  'src' : IDL.Text,
  'top' : IDL.Nat,
  'rotation' : IDL.Int,
  'zIndex' : IDL.Nat,
  'left' : IDL.Nat,
  'size' : IDL.Nat,
  'caption' : IDL.Text,
});
export const CardContent = IDL.Record({
  'loveCards' : IDL.Vec(LoveCard),
  'letterText' : IDL.Text,
  'uploadedImages' : IDL.Vec(IDL.Vec(IDL.Nat8)),
  'audioFileName' : IDL.Text,
  'uploadedAudio' : IDL.Vec(IDL.Vec(IDL.Nat8)),
  'galleryPhotos' : IDL.Vec(GalleryPhoto),
});

export const idlService = IDL.Service({
  'addAudio' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
  'addImage' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
  'getAudio' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Vec(IDL.Nat8))], []),
  'getContent' : IDL.Func([], [CardContent], []),
  'getImage' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Vec(IDL.Nat8))], []),
  'listAudio' : IDL.Func([], [IDL.Vec(IDL.Vec(IDL.Nat8))], []),
  'listImages' : IDL.Func([], [IDL.Vec(IDL.Vec(IDL.Nat8))], []),
  'replaceAudio' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat8)], [IDL.Bool], []),
  'replaceImage' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat8)], [IDL.Bool], []),
  'saveContent' : IDL.Func([CardContent], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LoveCard = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'photos' : IDL.Vec(IDL.Record({ 'src' : IDL.Text, 'rotation' : IDL.Int })),
  });
  const GalleryPhoto = IDL.Record({
    'src' : IDL.Text,
    'top' : IDL.Nat,
    'rotation' : IDL.Int,
    'zIndex' : IDL.Nat,
    'left' : IDL.Nat,
    'size' : IDL.Nat,
    'caption' : IDL.Text,
  });
  const CardContent = IDL.Record({
    'loveCards' : IDL.Vec(LoveCard),
    'letterText' : IDL.Text,
    'uploadedImages' : IDL.Vec(IDL.Vec(IDL.Nat8)),
    'audioFileName' : IDL.Text,
    'uploadedAudio' : IDL.Vec(IDL.Vec(IDL.Nat8)),
    'galleryPhotos' : IDL.Vec(GalleryPhoto),
  });
  
  return IDL.Service({
    'addAudio' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
    'addImage' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
    'getAudio' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Vec(IDL.Nat8))], []),
    'getContent' : IDL.Func([], [CardContent], []),
    'getImage' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Vec(IDL.Nat8))], []),
    'listAudio' : IDL.Func([], [IDL.Vec(IDL.Vec(IDL.Nat8))], []),
    'listImages' : IDL.Func([], [IDL.Vec(IDL.Vec(IDL.Nat8))], []),
    'replaceAudio' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat8)], [IDL.Bool], []),
    'replaceImage' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat8)], [IDL.Bool], []),
    'saveContent' : IDL.Func([CardContent], [], []),
  });
};

export const init = ({ IDL }) => { return []; };