/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CardContent {
  'loveCards' : Array<LoveCard>,
  'letterText' : string,
  'uploadedImages' : Array<Uint8Array>,
  'audioFileName' : string,
  'uploadedAudio' : Array<Uint8Array>,
  'galleryPhotos' : Array<GalleryPhoto>,
}
export interface GalleryPhoto {
  'src' : string,
  'top' : bigint,
  'rotation' : bigint,
  'zIndex' : bigint,
  'left' : bigint,
  'size' : bigint,
  'caption' : string,
}
export interface LoveCard {
  'title' : string,
  'description' : string,
  'photos' : Array<{ 'src' : string, 'rotation' : bigint }>,
}
export interface _SERVICE {
  'addAudio' : ActorMethod<[Uint8Array], undefined>,
  'addImage' : ActorMethod<[Uint8Array], undefined>,
  'getAudio' : ActorMethod<[bigint], [] | [Uint8Array]>,
  'getContent' : ActorMethod<[], CardContent>,
  'getImage' : ActorMethod<[bigint], [] | [Uint8Array]>,
  'listAudio' : ActorMethod<[], Array<Uint8Array>>,
  'listImages' : ActorMethod<[], Array<Uint8Array>>,
  'replaceAudio' : ActorMethod<[bigint, Uint8Array], boolean>,
  'replaceImage' : ActorMethod<[bigint, Uint8Array], boolean>,
  'saveContent' : ActorMethod<[CardContent], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];